namespace Firewind.Html;

using ColorCode;
using ColorCode.Styling;
using Microsoft.AspNetCore.Components;
using System.Net;
using System.Text;

/// <summary>
/// Formats source code into line-numbered HTML markup for display components.
/// </summary>
internal sealed class SourceCodeFormatter
{
    private static readonly string[] LineSeparators = ["\r\n", "\n", "\r"];
    private readonly HtmlFormatter formatter;

    /// <summary>
    /// Initializes a new instance of the <see cref="SourceCodeFormatter"/> class.
    /// </summary>
    /// <param name="style">
    /// Optional ColorCode style dictionary. When not provided, <see cref="StyleDictionary.DefaultDark"/> is used.
    /// </param>
    public SourceCodeFormatter(StyleDictionary? style = null)
        => this.formatter = new HtmlFormatter(style ?? StyleDictionary.DefaultDark, languageParser: null);

    /// <summary>
    /// Converts source code into line-numbered syntax-highlighted markup.
    /// </summary>
    /// <param name="sourceCode">The source code content to format.</param>
    /// <param name="language">The ColorCode language descriptor to use.</param>
    /// <returns>A <see cref="MarkupString"/> containing generated HTML.</returns>
    public MarkupString GetMarkupString(string sourceCode, ILanguage language)
    {
        ArgumentNullException.ThrowIfNull(sourceCode);
        ArgumentNullException.ThrowIfNull(language);

        var buffer = new StringBuilder();
        var lines = sourceCode.Split(LineSeparators, StringSplitOptions.None);

        for (var i = 0; i < lines.Length; i++)
        {
            buffer.Append("<pre data-prefix=\"")
                  .Append(i + 1)
                  .Append("\"><code>")
                  .Append(this.GetLineMarkup(lines[i], language))
                  .Append("</code></pre>");
        }

        return new MarkupString(buffer.ToString());
    }

    /// <summary>
    /// Formats a single line of source code and removes wrapping <c>pre</c> tags generated by ColorCode.
    /// </summary>
    /// <param name="line">The source line to format.</param>
    /// <param name="language">The ColorCode language descriptor to use.</param>
    /// <returns>Formatted HTML content for the line.</returns>
    private string GetLineMarkup(string line, ILanguage language)
    {
        if (string.IsNullOrEmpty(line))
        {
            return string.Empty;
        }

        const string preOpenTag = "<pre>";
        const string preCloseTag = "</pre>";

        var html = this.formatter.GetHtmlString(line, language);
        var preStart = html.IndexOf(preOpenTag, StringComparison.OrdinalIgnoreCase);
        var preEnd = html.IndexOf(preCloseTag, StringComparison.OrdinalIgnoreCase);
        if (preStart < 0 || preEnd <= preStart)
        {
            return WebUtility.HtmlEncode(line);
        }

        var contentStart = preStart + preOpenTag.Length;
        var contentLength = preEnd - contentStart;
        return html.Substring(contentStart, contentLength).Trim('\r', '\n');
    }
}
